export const DRAG_PIN = "DRAG_PIN";
export const CHANGE_PLAYING = "CHANGE_PLAYING";
export const CHANGE_DURATION = "CHANGE_DURATION";
export const CHANGE_VIDEO = "CHANGE_VIDEO";
export const CHANGE_CURRENT_TIME = "CHANGE_CURRENT_TIME";
